export const words = [
  'a',
  'again',
  'all',
  'also',
  'and',
  'another',
  'any',
  'around',
  'as',
  'ask',
  'at',
  'back',
  'because',
  'become',
  'before',
  'begin',
  'both',
  'but',
  'by',
  'call',
  'can',
  'change',
  'child',
  'come',
  'could',
  'course',
  'day',
  'develop',
  'each',
  'early',
  'end',
  'even',
  'eye',
  'face',
  'fact',
  'few',
  'first',
  'follow',
  'from',
  'general',
  'get',
  'give',
  'good',
  'govern',
  'group',
  'hand',
  'have',
  'he',
  'head',
  'help',
  'here',
  'high',
  'hold',
  'home',
  'how',
  'however',
  'if',
  'increase',
  'interest',
  'it',
  'know',
  'large',
  'last',
  'lead',
  'leave',
  'life',
  'like',
  'line',
  'little',
  'look',
  'make',
  'man',
  'may',
  'mean',
  'might',
  'more',
  'must',
  'need',
  'never',
  'new',
  'no',
  'now',
  'number',
  'of',
  'off',
  'old',
  'on',
  'one',
  'open',
  'or',
  'order',
  'out',
  'over',
  'own',
  'part',
  'people',
  'person',
  'place',
  'plan',
  'play',
  'point',
  'possible',
  'present',
  'problem',
  'program',
  'public',
  'real',
  'right',
  'run',
  'say',
  'see',
  'seem',
  'show',
  'small',
  'some',
  'stand',
  'state',
  'still',
  'such',
  'system',
  'take',
  'than',
  'that',
  'the',
  'then',
  'there',
  'these',
  'they',
  'thing',
  'think',
  'this',
  'those',
  'time',
  'to',
  'under',
  'up',
  'use',
  'very',
  'way',
  'what',
  'when',
  'where',
  'while',
  'will',
  'with',
  'without',
  'work',
  'world',
  'would',
  'write',
  'you',
  'she',
  'set',
  'we',
  'long',
  'in',
  'many',
  'do',
  'after',
  'which',
  'so',
  'same',
  'other',
  'house',
  'during',
  'much',
  'just',
  'consider',
  'since',
  'should',
  'only',
  'tell',
  'about',
];

export const frases = [
  'Soy demasiado impresionante como para aceptar un no por respuesta.',
  'El traje es mi armadura. Las mujeres, mis debilidades.',
  'El playbook es la biblia del ligoteo.',
  'Legen... wait for it... dary!', // ¡Legendario! (Su famosa frase)
  'Chicas, a mí me gustan las mujeres que saben lo que quieren. Y lo que yo quiero es a ti.',
  'No soy un jugador, soy un profesional.',
  'El amor es como un láser. Concéntrate en una sola chica y ella será tuya.',
  'Las chicas son como autobuses. Si pierdes uno, siempre habrá otro en camino.',
  'El único límite es tu imaginación.',
  'La vida es corta, así que vívela al máximo.',

  // Frases sobre la vida y la amistad
  'La diferencia entre un buen amigo y un gran amigo es que un gran amigo te ayuda a mudarte.',
  'No hay nada mejor que una buena botella de whisky y la compañía de buenos amigos.',
  'La vida es un viaje, disfrútalo.',
  'No tengas miedo de correr riesgos. Lo peor que puede pasar es que te diviertas.',
  'La única manera de hacer un buen trabajo es amar lo que haces.',
  'El éxito es la mejor venganza.',
  'No hay nada que no puedas lograr si te lo propones.',
  'El futuro es tuyo. Hazlo lo mejor que puedas.',
  'La vida es demasiado corta como para ser infeliz. Sé feliz.',

  // Frases divertidas
  "Soy tan bueno en la cama que me apodan 'El Mago'.",
  'Tengo más estilo que un pavo real en un desfile de moda.',
  'Soy tan guapo que podría derretir el hielo del Ártico.',
  'Soy tan divertido que podría hacer reír a una estatua.',
  'Soy tan inteligente que podría resolver la teoría de la relatividad en 10 segundos.',
  'Soy tan rico que podría comprar todo Manhattan.',
  'Soy tan famoso que soy conocido en todo el mundo.',
  'Soy tan increíble que no hay palabras para describirme.',
  'Soy tan legendario que mi nombre pasará a la historia.',
  'No soy un hombre de negocios, soy un empresario.',
  'No pido perdón, soy un Shelby.',
  'Un hombre puede ser destruido, pero no derrotado.',
  'En este mundo, hay dos tipos de personas: los que tienen miedo y los que hacen miedo.',
  'El miedo es solo una ilusión. Y la ilusión se puede superar.',
  'El pasado no se puede cambiar. El futuro no se puede predecir. El presente es lo único que tenemos.',
  'La familia es lo único que importa.',
  'Los enemigos son como los ratones. Siempre hay que estar vigilando.',
  'La confianza es algo que se gana, no que se da.',
  'Un hombre es tan bueno como sus palabras.',
  'El poder no se toma, se arrebata.',
  'No hay nada más peligroso que un hombre sin nada que perder.',
  'La única manera de salir del infierno es atravesarlo.',
  'El tiempo es lo más valioso que tenemos.',
  'La muerte es solo el final de una vida, no el final de todo.',
  'No hay nada que temer, excepto al miedo mismo.',
  'La venganza es un plato que se sirve frío.',
  'La lealtad es lo único que realmente importa.',
  'El dinero es solo papel. El poder es lo que realmente importa.',
  'Nunca subestimes a tus enemigos.',
  'Siempre ten un plan.',
  'Nunca confíes en nadie.',
  'El enemigo de mi enemigo es mi amigo.',
  'La guerra es el infierno.',
  'La paz es solo una ilusión.',
  'El amor es una debilidad.',
  'La familia es lo único que te mantendrá a salvo.',
  'Nunca te rindas.',
  'No hay nada que no puedas lograr si te lo propones.',
  'El futuro es tuyo. Tómalo.',
  'Bazinga!',
  'El universo funciona de acuerdo a leyes inmutables de la física. No hay lugar para la magia o la superstición.',
  'Soy un científico, no un mago.',
  'La teoría de la relatividad es una de las teorías más elegantes y bellas de la física.',
  'La matemática es el lenguaje del universo.',
  'No soy un nerd, soy un teórico físico.',
  'La ciencia es la única forma de comprender el mundo que nos rodea.',
  'No creo en la astrología, es una pseudociencia.',
  'Soy un experto en la teoría de cuerdas.',
  'La ciencia es la clave para resolver todos los problemas de la humanidad.',

  // Frases sobre la vida y las relaciones
  'No soy capaz de entender las emociones humanas.',
  'No tengo amigos, tengo compañeros de trabajo.',
  'No soy bueno con las mujeres, pero soy un genio.',
  'No me gusta el cambio, prefiero la rutina.',
  'Soy muy particular con mis hábitos y costumbres.',
  'No soy un fanático del contacto físico.',
  'Soy un nerd orgulloso.',
  'No soy capaz de mentir.',
  'No soy muy bueno para las bromas.',
  'Soy un gran fanático de Star Trek y Star Wars.',

  // Frases divertidas y excéntricas
  '¡No es necesario gritar!',
  '¿Cuál es tu teoría sobre esto?',
  'Me gusta la comida cómoda y la ropa interior de colores brillantes.',
  'Soy un experto en juegos de mesa.',
  'No soy bueno para bailar, pero puedo tocar el theremin.',
  'Soy un gran fanático de los cómics.',
  'No me gusta el cambio, prefiero la rutina.',
  'Soy un poco obsesivo-compulsivo.',
  'Soy un gran fanático de las películas de superhéroes.',
  'No soy capaz de entender el sarcasmo.',
];
